config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :parks, except: [:show] do
    collection do
      get :search
    end
  end

  namespace :api do
    namespace :v1 do
      resources :parks, only: [:index, :show, :create]
      resources :reviews, only: [:index, :show, :create]
      resources :votes
      resources :users
    end
  end

  root 'parks#index'
  get "*path", to: 'parks#index'

end

app/models/amenity.rb
class Amenity < ApplicationRecord
  has_many :park_amenities
  has_many :parks, through: :park_amenities

  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/park.rb
class Park < ApplicationRecord
  has_many :reviews
  has_many :park_amenities
  has_many :amenities, through: :park_amenities
  belongs_to :user

  validates :name, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true
  validates :category, presence: true

  def self.search(search)
    where("name ILIKE ? OR address ILIKE ? OR city ILIKE ? OR state ILIKE ? OR zip ILIKE ? OR category ILIKE ? OR description ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%, %#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
  end

    STATES = [
    ["AK", "Alaska"],
    ["AL", "Alabama"],
    ["AR", "Arkansas"],
    ["AS", "American Samoa"],
    ["AZ", "Arizona"],
    ["CA", "California"],
    ["CO", "Colorado"],
    ["CT", "Connecticut"],
    ["DC", "District of Columbia"],
    ["DE", "Delaware"],
    ["FL", "Florida"],
    ["GA", "Georgia"],
    ["GU", "Guam"],
    ["HI", "Hawaii"],
    ["IA", "Iowa"],
    ["ID", "Idaho"],
    ["IL", "Illinois"],
    ["IN", "Indiana"],
    ["KS", "Kansas"],
    ["KY", "Kentucky"],
    ["LA", "Louisiana"],
    ["MA", "Massachusetts"],
    ["MD", "Maryland"],
    ["ME", "Maine"],
    ["MI", "Michigan"],
    ["MN", "Minnesota"],
    ["MO", "Missouri"],
    ["MS", "Mississippi"],
    ["MT", "Montana"],
    ["NC", "North Carolina"],
    ["ND", "North Dakota"],
    ["NE", "Nebraska"],
    ["NH", "New Hampshire"],
    ["NJ", "New Jersey"],
    ["NM", "New Mexico"],
    ["NV", "Nevada"],
    ["NY", "New York"],
    ["OH", "Ohio"],
    ["OK", "Oklahoma"],
    ["OR", "Oregon"],
    ["PA", "Pennsylvania"],
    ["PR", "Puerto Rico"],
    ["RI", "Rhode Island"],
    ["SC", "South Carolina"],
    ["SD", "South Dakota"],
    ["TN", "Tennessee"],
    ["TX", "Texas"],
    ["UT", "Utah"],
    ["VA", "Virginia"],
    ["VI", "Virgin Islands"],
    ["VT", "Vermont"],
    ["WA", "Washington"],
    ["WI", "Wisconsin"],
    ["WV", "West Virginia"],
    ["WY", "Wyoming"]
  ]

  CATEGORIES = [
    "National",
    "State",
    "Amusement",
    "Water",
    "Marine",
    "Nature",
    "Other"
  ]
end

app/models/park_amenity.rb
class ParkAmenity < ApplicationRecord
  belongs_to :park
  belongs_to :amenity
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :park
  belongs_to :user
  has_many :votes

  validates :rating, presence: true

  def down_votes
    count = 0
    votes.each do |vote|
      if vote.vote_value == -1
        count += 1
      end
    end
    count
  end

  def up_votes
    count = 0
    votes.each do |vote|
      if vote.vote_value == 1
        count += 1
      end
    end
    count
  end

  def net_votes
    up_votes - down_votes
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :parks
  has_many :reviews
  has_many :votes

  validates_presence_of :first_name
  validates_presence_of :last_name
  validates :email, presence: true
  mount_uploader :profile_photo, ProfilePhotoUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  def admin?
    role == "admin"
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/controllers/api/v1/parks_controller.rb
class Api::V1::ParksController < ApplicationController
  # serialization_scope :current_user

  def index
    # render json: { parks: Park.all, user: current_user }
    render json: Park.all
  end

  def show
    # park = Park.find(params[:id])
    # render json: { park: park, reviews: park.reviews, user: current_user }
    render json: Park.find(params[:id]), serializer: ParkShowSerializer
  end


  def create
    park = Park.new(
      name: params[:name],
      address: params[:address],
      city: params[:city],
      state: params[:state],
      zip: params[:zip],
      category: params[:category],
      description: params[:description],
      photo_url: params[:photo_url],
      size: params[:size].to_i,
      user_id: current_user.id
    )


    if park.save
      render json: { park: park }
    else
      render json: { error: park.errors.full_messages }, status: :unprocessable_entity
    end
  end
end

app/controllers/api/v1/reviews_controller.rb
class Api::V1::ReviewsController < ApplicationController
  def index
    render json: Review.all
  end

  def create
    review = Review.new(new_review_params)
    if review.save
      render json: { review: review }
    else
      render json: { error: review.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def new_review_params
    params.require(:review).permit(:rating, :body, :park_id, :user_id)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController

  def index
    render json: { users: User.all, current_user: current_user }
  end

  def show
    render json: current_user, serializer: UserShowSerializer
  end

end

app/controllers/api/v1/votes_controller.rb
class Api::V1::VotesController < ApplicationController
  def index
    render json: Vote.all
  end

  def create
    vote = Vote.new(
      user_id: params[:user_id],
      review_id: params[:review_id],
      vote_value: params[:vote_value]
    )

    if vote.save
      render json: { vote: vote }
    else
      render json: { error: park.errors.full_messages }, status: :unprocessable_entity
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  skip_before_action :verify_authenticity_token

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :profile_photo])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :profile_photo])
  end
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  before_action :authorize_user, except: [:index, :search]

  def index
  end

  def search
    if params[:search]
      @parks = Park.search(params[:search]).order("created_at DESC")
    else
      @parks = Park.all.order("created_at DESC")
    end
  end

  def authorize_user
    if !user_signed_in? || !current_user.admin?
      raise ActionController::RoutingError.new("Not Found")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "ParkIt" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="top-bar" data-topbar role="navigation">
      <section class="top-bar-section">
        <ul class= "left">
          <li class="name"><%= link_to 'ParkIt', parks_path %></li>
        </ul>

        <ul class="right">
          <li class="has-form">
            <div class="row collapse">
              <div class="large-8 small-9 columns">
                <li><%= form_tag(search_parks_path, method: :get) do %></li>
                <li><%= search_field_tag :search, params[:search], placeholder: "Search Parks", required: "required"%></li>
                <li><%= submit_tag "Search", class: "radius button", :name => nil %></li>
                <li><% end %></li>

                <li><%- if user_signed_in? -%></li>
                <ul class="menu_text">
                  <li><% unless current_user.profile_photo.file.nil? %></li>
                  <div id="profile-photo-container">
                    <li id="profile-photo"><%= image_tag current_user.profile_photo.url, { size: "50x80" } %></li>
                  </div>
                  <li><% end %></li>
                </ul>
                <li><% end %></li>

              <a href='#' data-reveal-id="firstModal" class="icon" style="float: right;">&#9776;</a>
              <div id="firstModal" class="reveal-modal" data-reveal aria-labelledby="firstModalTitle" aria-hidden="true" role="dialog">
                <h2 id="firstModalTitle">Welcome to ParkIt!</h2>
                <%- if user_signed_in? -%>
                <ul><%= link_to 'Update Account', edit_user_registration_path, method: :get %></ul>
                <ul><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></ul>
                <% if current_user.admin? %>
                <ul><%= link_to "Admin Section", admin_path %></ul>
                <% end %>
                <%- else -%>
                <ul><%= link_to 'Sign In', new_user_session_path %></ul>
                <ul><%= link_to 'Sign Up', new_user_registration_path %></ul>
                <%- end -%>
                <a class="close-reveal-modal" aria-label="Close">&#215;</a>
              </div>
            </ul>
            </div>

          </div>

          <% if flash.any? %>

          <div class="flash">
            <% flash.each do |name, msg| %>
            <%= content_tag :div, msg, class: "callout #{name}" %>
            <% end %>
          </div>
          <% end %>

          <%= yield %>
          <%= javascript_include_tag "application" %>
          <br>

  </body>
</html>

app/views/parks/index.html.erb
<div id="app"></div>

app/views/parks/search.html.erb
<% if @parks.blank? %>
  <h4>There are no parks containing the term <%= params[:search] %>.</h4>
<% else %>
  <% @parks.each do |park| %>
    <h3><%= park.name %></h3>
    <img width="200px" height="200px" src=<%=park.photo_url %> />
    <ul></br>
      <%= park.address %></br>
      <%= park.city %>, <%= park.state %> <%= park.zip %></br>
      Type of park: <%= park.category %></br>
      Description: <%= park.description %></br>
    </ul>
  <% end %>
<% end %>

</br><%= link_to 'Back', parks_path %>